learning:

  model_name: "generic_model"

  learning_rate: 0.0001
  weight_decay: 0.02
  batch_size: 16
  epochs: 1000
  beta_ema: 0.9999
  gradient_clip: 0.1
  save_path: "weights/vqvae"
  eval_split_factor: 0.01
  amp: False
  num_devices: 1
  num_workers: 0
  val_split: 0.01

  loss_monitor: "step"
  interval: "training_total_loss"
  frequency: 1

dataset:
  dataset_type: "music_dataset"
  data_module_type: "basic"
  sample_rate: 44100
  data_dir: "data"
  slice_length: 262144
  preload: True
  device: "cpu"
  preload_data_dir: "data"

image_mel_spec_params:
  n_fft: 2048
  hop_length: 512
  n_mels: 128
  power: 0.5
  f_min: 20
  pad_mode: "reflect"
  norm: "slaney"
  mel_scale: "htk"
