learning:

  model_name: "generic_model"

  learning_rate: 0.0001
  weight_decay: 0.02
  batch_size: 16
  epochs: 1000
  beta_ema: 0.9999
  gradient_clip: 0.1
  save_path: "weights/vqvae"
  eval_split_factor: 0.01
  amp: False
  num_devices: 1
  num_workers: 0

  loss_monitor: "step"
  interval: "training_total_loss"
  frequency: 1