learning:

  model_name: "generic_model"

  learning_rate: 0.0001
  weight_decay: 0.02
  batch_size: 2
  epochs: 1000
  beta_ema: 0.9999
  gradient_clip: 0.1
  save_path: "weights/vqvae"
  eval_split_factor: 0.01
  amp: False
  num_devices: 1
  num_workers: 0
  val_split: 0.01

  loss_monitor: "training_total_loss"
  interval: "epoch"
  frequency: 1

dataset:
  dataset_type: "test"
  data_module_type: "basic"
  sample_rate: 44100
  data_dir: "data"
  slice_length: 32768
  preload: True
  device: "cpu"
  preload_data_dir: "data"

image_mel_spec_params:
  n_fft: 2048
  hop_length: 257 # Apparently 257 is the only hop-length that diffwave works with?
  n_mels: 128
  power: 0.5
  f_min: 20
  pad_mode: "reflect"
  norm: "slaney"
  mel_scale: "htk"
  pad: 0

diffusion: 
  num_steps: 50
  scheduler: "linear"

loss:

  aggregator_type: "weighted_sum"

  reconstruction_loss:
    type: "rec"
    weight: 1.0
    base_loss_type: 'mse'
    phase_parameter: 1

  melspec_loss_1:
    type: "melspec"
    weight: 1.0
    base_loss_type: 'l1'
    lin_start: 1.0
    lin_end: 1.0
    
    melspec_params:
      n_fft: 2048
      hop_length: 256
      n_mels: 128
      pad_mode: reflect
      f_min: 20
      power: 1.0
      pad: 0
      norm: "slaney"
      mel_scale: "htk"

  melspec_loss_2:
    type: "melspec"
    weight: 1.0
    base_loss_type: 'l1'
    lin_start: 1.0
    lin_end: 1.0

    melspec_params:
      n_fft: 1024
      hop_length: 128
      n_mels: 128
      pad_mode: reflect
      f_min: 20
      power: 2.0
      pad: 0
      norm: "slaney"
      mel_scale: "htk"

  melspec_loss_3:
    type: "melspec"
    weight: 1.0
    base_loss_type: 'l1'
    lin_start: 0.1
    lin_end: 20

    melspec_params:
      n_fft: 512
      hop_length: 128
      n_mels: 64
      pad_mode: reflect
      f_min: 20
      power: 1.0
      pad: 0
      norm: "slaney"
      mel_scale: "htk"

  melspec_loss_4:
    type: "melspec"
    weight: 5.0
    base_loss_type: 'l1'
    lin_start: 0.5
    lin_end: 10.0
    
    melspec_params:
      n_fft: 2048
      hop_length: 256
      n_mels: 128
      pad_mode: reflect
      f_min: 20
      power: 1.0
      pad: 0
      norm: "slaney"
      mel_scale: "htk"

  melspec_loss_5:
    type: "melspec"
    weight: 5.0
    base_loss_type: 'l1'
    lin_start: 0.1
    lin_end: 20

    melspec_params:
      n_fft: 512
      hop_length: 256
      n_mels: 64
      pad_mode: reflect
      f_min: 20
      power: 2.0
      pad: 0
      norm: "slaney"
      mel_scale: "htk"